version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15
    container_name: goodhands-postgres
    environment:
      POSTGRES_DB: goodhands
      POSTGRES_USER: goodhands_user
      POSTGRES_PASSWORD: GH2025_SecureDB_Pass_9x7w2k5n8m3q1p6z
    volumes:
      - goodhands_postgres_data:/var/lib/postgresql/data
    networks:
      - goodhands_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goodhands_user -d goodhands"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FastAPI 백엔드
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: goodhands-backend
    environment:
      DATABASE_URL: postgresql://goodhands_user:GH2025_SecureDB_Pass_9x7w2k5n8m3q1p6z@postgres:5432/goodhands
      SECRET_KEY: GH2025_JWT_SecretKey_4a8f2d7c9b5e3h6j1k8m2n5p
      ENVIRONMENT: production
      DEBUG: false
      BASE_URL: https://pay.gzonesoft.co.kr
      CORS_ORIGINS: '["https://pay.gzonesoft.co.kr", "https://www.pay.gzonesoft.co.kr"]'
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - goodhands_uploads:/app/uploads
      - goodhands_logs:/app/logs
    networks:
      - goodhands_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx with SSL
  nginx:
    image: nginx:alpine
    container_name: goodhands-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - goodhands_nginx_conf:/etc/nginx/nginx.conf:ro
      - goodhands_ssl:/etc/nginx/ssl:ro
      - goodhands_uploads:/var/www/uploads:ro
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - goodhands_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  goodhands_postgres_data:
    name: goodhands_postgres_data
  goodhands_uploads:
    name: goodhands_uploads
  goodhands_logs:
    name: goodhands_logs
  goodhands_nginx_conf:
    name: goodhands_nginx_conf
  goodhands_ssl:
    name: goodhands_ssl

networks:
  goodhands_network:
    name: goodhands_network
    driver: bridge
